Repository boostcampwm-2022/web01-knoticle, pull requests merged in 2022-11, with the labels that each got.

#17 Modal 컴포넌트 작업
  frontend/assets/ico_backward.svg
  frontend/assets/ico_cancel.svg
  frontend/components/common/Modal/index.tsx
  frontend/components/common/Modal/styled.ts
  frontend/pages/api/hello.ts
  frontend/pages/modaltest.tsx
Labels: FEAT, FE

#18 Github OAuth 로그인 구현
  backend/.gitignore
  backend/package-lock.json
  backend/package.json
  backend/prisma/migrations/20221115100900_init/migration.sql
  backend/prisma/schema.prisma
  backend/src/apis/auth/auth.controller.ts
  backend/src/apis/auth/auth.service.ts
  backend/src/apis/index.ts
  frontend/.gitignore
  frontend/layouts/SignInModal.tsx
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/github.tsx
Labels: FEAT, BE, FE

#19 로그인 모달 컴포넌트 작업
  frontend/assets/ico_article.svg
  frontend/assets/ico_person.svg
  frontend/assets/ico_search.svg
  frontend/components/SignInModal/ModalTitle.tsx
  frontend/components/SignInModal/index.tsx
  frontend/components/common/Button.tsx
  frontend/components/common/GNB/index.tsx
  frontend/components/common/GNB/styled.ts
  frontend/components/common/LabeledInput/index.tsx
  frontend/components/common/LabeledInput/styled.ts
  frontend/components/common/Modal/ModalButton.tsx
  frontend/components/common/Modal/styled.ts
  frontend/layouts/SignInModal.tsx
  frontend/pages/index.tsx
  frontend/styles/common.ts
  frontend/styles/layout.ts
Labels: FEAT, FE

#25 에디터 페이지 UI 작업
  frontend/assets/ico_caret_down.svg
  frontend/components/edit/Dropdown/index.tsx
  frontend/components/edit/Dropdown/styled.ts
  frontend/components/edit/EditBar/index.tsx
  frontend/components/edit/EditBar/styled.ts
  frontend/components/edit/Editor/index.tsx
  frontend/components/edit/Editor/styled.ts
  frontend/components/edit/PublishModal/index.tsx
  frontend/components/edit/PublishModal/styled.ts
  frontend/pages/editor.tsx
Labels: FEAT, FE

#29 책 컴포넌트 UI 작업
  frontend/assets/ico_bookmark.svg
  frontend/assets/ico_more_contents.svg
  frontend/assets/img_sample_thumbnail.JPG
  frontend/components/common/Book/index.tsx
  frontend/components/common/Book/styled.ts
  frontend/styles/layout.ts
Labels: FEAT, FE

#32 검색 페이지 UI 작업
  backend/prisma/migrations/migration_lock.toml
  frontend/assets/img_profile.png
  frontend/components/search/SearchBar/index.tsx
  frontend/components/search/SearchBar/styled.ts
  frontend/components/search/SearchFilter/index.tsx
  frontend/components/search/SearchFilter/styled.ts
  frontend/components/search/SearchListItem/index.tsx
  frontend/components/search/SearchListItem/styled.ts
  frontend/components/search/styled.ts
  frontend/pages/search.tsx
Labels: FEAT, FE

#33 뷰어 페이지 UI 작업
  frontend/assets/ico_article.svg
  frontend/assets/ico_hide.svg
  frontend/assets/ico_leftBtn.svg
  frontend/assets/ico_original.svg
  frontend/assets/ico_rightBtn.svg
  frontend/assets/ico_sampleProfile.svg
  frontend/assets/ico_scrap.svg
  frontend/components/Viewer/ArticleContent/Button/index.tsx
  frontend/components/Viewer/ArticleContent/Button/styled.ts
  frontend/components/Viewer/ArticleContent/index.tsx
  frontend/components/Viewer/ArticleContent/sampledata.ts
  frontend/components/Viewer/ArticleContent/styled.ts
  frontend/components/Viewer/TOC/index.tsx
  frontend/components/Viewer/TOC/styled.ts
  frontend/pages/viewer.tsx
  frontend/styles/layout.ts
Labels: FEAT, FE

#34 메인 페이지 UI 작업
  frontend/assets/ico_arrow_right.svg
  frontend/assets/ico_flower.svg
  frontend/components/Slider/index.tsx
  frontend/components/Slider/styled.ts
  frontend/components/common/Footer/index.tsx
  frontend/components/common/Footer/styled.ts
  frontend/pages/index.tsx
  frontend/styles/layout.ts
Labels: FEAT, FE

#35 프로젝트 모듈 절대 경로 설정
  README.md
  backend/.eslintrc.js
  backend/package-lock.json
  backend/package.json
  backend/src/apis/auth/auth.controller.ts
  backend/src/apis/auth/auth.service.ts
  backend/src/apis/index.ts
  backend/src/index.ts
  backend/src/loaders/express.loader.ts
  backend/src/utils/catch-async.ts
  backend/tsconfig.json
  frontend/.eslintrc.json
  frontend/README.md
  frontend/components/SignInModal/index.tsx
  frontend/components/common/GNB/index.tsx
  frontend/components/common/LabeledInput/index.tsx
  frontend/components/common/Modal/index.tsx
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/index.tsx
  frontend/styles/GlobalStyle.ts
  frontend/styles/common.ts
  frontend/tsconfig.json
Labels: FEAT, BE, FE

#36 데이터베이스 스키마 변경 및 액세스 토큰 페이로드 변경
  backend/prisma/schema.prisma
  backend/src/apis/auth/auth.controller.ts
  backend/src/apis/auth/auth.service.ts
Labels: FEAT, BE

#74 뷰어페이지 스타일 수정
  frontend/components/Viewer/TOC/index.tsx
  frontend/components/Viewer/TOC/styled.ts
Labels: FE

#75 단일 책 조회 book api 개발
  backend/src/apis/books/books.controller.ts
  backend/src/apis/books/books.service.ts
  backend/src/apis/index.ts
  backend/src/errors/messages.ts
Labels: FEAT, BE

#76 Article, Scrap 생성
  backend/.eslintrc.js
  backend/src/apis/article/article.controller.ts
  backend/src/apis/article/article.interface.ts
  backend/src/apis/article/article.service.ts
  backend/src/apis/index.ts
  backend/src/apis/scrap/scrap.interface.ts
  backend/src/apis/scrap/scrap.service.ts
Labels: FEAT, BE

#78 뷰어 페이지 사이드바 FE 작업
  frontend/components/Viewer/ArticleContent/styled.ts
  frontend/components/Viewer/TOC/index.tsx
  frontend/components/Viewer/TOC/styled.ts
  frontend/pages/viewer.tsx
  frontend/pages/viewer/[...data].tsx
Labels: FEAT, FE

#79 NCP에 이미지 업로드
  backend/package-lock.json
  backend/package.json
  backend/src/apis/image/image.controller.ts
  backend/src/apis/image/image.interface.ts
  backend/src/apis/image/image.service.ts
  backend/src/apis/index.ts
Labels: FEAT, BE

#80 임시 글 생성 및 조회
  backend/src/apis/article/article.controller.ts
  backend/src/apis/article/article.interface.ts
  backend/src/apis/article/article.service.ts
  backend/src/apis/index.ts
Labels: FEAT, BE

#82 단일 글 조회 api 개발
  backend/src/apis/articles/articles.controller.ts
  backend/src/apis/articles/articles.service.ts
  backend/src/apis/books/books.controller.ts
  backend/src/apis/index.ts
  backend/src/errors/messages.ts
  frontend/assets/ico_bookmark.svg
Labels: FEAT, BE

#83 회원가입 기능 구현
  backend/package-lock.json
  backend/package.json
  backend/src/apis/auth/auth.controller.ts
  backend/src/apis/auth/auth.service.ts
  backend/src/apis/index.ts
  backend/src/errors/index.ts
  backend/src/errors/messages.ts
  frontend/components/SignUpModal/index.tsx
  frontend/components/SignUpModal/styled.ts
  frontend/components/common/GNB/index.tsx
  frontend/components/common/Modal/ModalButton/index.tsx
Labels: FEAT, BE, FE

#84 마크다운 에디터 작업
  frontend/components/edit/Editor/index.tsx
  frontend/components/edit/Editor/styled.ts
  frontend/components/edit/Preview/index.tsx
  frontend/components/edit/Preview/styled.ts
  frontend/hooks/useInput.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/tsconfig.json
Labels: FEAT, FE

#85 [수정] Eslint 및 폴더명 통일 작업
  backend/.eslintrc.js
  backend/src/apis/article/article.controller.ts
  backend/src/apis/article/article.service.ts
  backend/src/apis/articles/articles.controller.ts
  backend/src/apis/articles/articles.interface.ts
  backend/src/apis/articles/articles.service.ts
  backend/src/apis/auth/auth.service.ts
  backend/src/apis/books/books.controller.ts
  backend/src/apis/images/images.controller.ts
  backend/src/apis/images/images.interface.ts
  backend/src/apis/images/images.service.ts
  backend/src/apis/index.ts
  backend/src/apis/scraps/scraps.interface.ts
  backend/src/apis/scraps/scraps.service.ts
  frontend/assets/img_sample_thumbnail.jpg
  frontend/components/SignInModal/index.tsx
  frontend/components/home/Slider/index.tsx
  frontend/components/home/Slider/styled.ts
  frontend/components/viewer/ArticleContent/Button/index.tsx
  frontend/components/viewer/ArticleContent/Button/styled.ts
  frontend/components/viewer/ArticleContent/index.tsx
  frontend/components/viewer/ArticleContent/sampledata.ts
  frontend/components/viewer/ArticleContent/styled.ts
  frontend/components/viewer/ClosedSideBar/index.tsx
  frontend/components/viewer/ClosedSideBar/styled.ts
  frontend/components/viewer/TOC/index.tsx
  frontend/components/viewer/TOC/styled.ts
  frontend/pages/index.tsx
  frontend/pages/viewer/[...data].tsx
Labels: BE, FE, IMPROVE

#86 [수정] 회원가입 PR 수정사항 반영
  backend/src/apis/auth/auth.controller.ts
  backend/src/apis/auth/auth.service.ts
  frontend/components/SignInModal/index.tsx
  frontend/components/SignInModal/styled.ts
Labels: BE, FE, IMPROVE

#88 Article 생성 작업
  backend/prisma/schema.prisma
  backend/src/apis/articles/articles.controller.ts
  backend/src/apis/articles/articles.interface.ts
  backend/src/apis/articles/articles.service.ts
  frontend/.eslintrc.json
  frontend/apis/articleApi.ts
  frontend/apis/bookApi.ts
  frontend/atoms/article.ts
  frontend/components/Viewer/ArticleContent/Button/index.tsx
  frontend/components/Viewer/ArticleContent/Button/styled.ts
  frontend/components/Viewer/ArticleContent/index.tsx
  frontend/components/Viewer/ArticleContent/sampledata.ts
  frontend/components/Viewer/ArticleContent/styled.ts
  frontend/components/Viewer/TOC/index.tsx
  frontend/components/Viewer/TOC/styled.ts
  frontend/components/edit/Dropdown/index.tsx
  frontend/components/edit/Editor/index.tsx
  frontend/components/edit/PublishModal/index.tsx
  frontend/hooks/useFetch.ts
  frontend/interfaces/article.interface.ts
  frontend/interfaces/book.interface.ts
  frontend/interfaces/index.ts
  frontend/interfaces/scrap.interface.ts
  frontend/pages/editor.tsx
  frontend/tsconfig.json
  frontend/utils/api.ts
Labels: FEAT, FE

#89 토큰 guard 미들웨어 추가
  backend/package-lock.json
  backend/package.json
  backend/src/apis/auth/auth.controller.ts
  backend/src/apis/auth/auth.service.ts
  backend/src/errors/messages.ts
  backend/src/loaders/express.loader.ts
  backend/src/middlewares/tokenValidator.ts
  backend/src/utils/token.ts
Labels: FEAT, BE

#87 책 컴포넌트 링크 및 북마트 이벤트 추가
  frontend/assets/ico_bookmark_black.svg
  frontend/assets/ico_bookmark_red.svg
  frontend/components/common/Book/index.tsx
  frontend/components/common/Book/styled.ts
  frontend/components/home/Slider/index.tsx
  frontend/components/home/Slider/tempBookData.ts
Labels: FEAT, FE

#91 뷰어페이지 글 삭제 기능
  backend/src/apis/articles/articles.controller.ts
  backend/src/apis/articles/articles.service.ts
  backend/src/apis/index.ts
  backend/src/errors/messages.ts
  frontend/components/viewer/ArticleContent/index.tsx
  frontend/pages/viewer/[...data].tsx
Labels: FEAT, BE, FE

#92 북마크 API 개발
  backend/src/apis/bookmarks/bookmarks.controller.ts
  backend/src/apis/bookmarks/bookmarks.service.ts
  backend/src/apis/index.ts
  backend/src/errors/messages.ts
Labels: FEAT, BE

#93 책 리스트 조회 API 작업
  backend/src/apis/articles/articles.service.ts
  backend/src/apis/auth/auth.service.ts
  backend/src/apis/books/books.controller.ts
  backend/src/apis/books/books.interface.ts
  backend/src/apis/books/books.service.ts
  backend/src/apis/index.ts
  backend/src/errors/error.ts
  backend/src/errors/index.ts
  backend/src/errors/message.ts
  backend/src/middlewares/tokenDecoder.ts
  backend/tsconfig.json
Labels: FEAT, BE

#97 책 조회 API에서 비로그인 유저 요청 시 발생하는 오류 수정
  backend/src/apis/books/books.controller.ts
  backend/src/apis/books/books.service.ts
Labels: BE, IMPROVE

#96 useBookmark 훅 추가 및 TOC 컴포넌트 북마크 이벤트 등록
  frontend/apis/bookmarkApi.ts
  frontend/assets/ico_bookmark_grey_filled.svg
  frontend/assets/ico_bookmark_white_filled.svg
  frontend/components/common/Book/index.tsx
  frontend/components/viewer/TOC/index.tsx
  frontend/hooks/useBookmark.ts
Labels: FEAT, FE

#99 메인 페이지 책 리스트 보여주기
  backend/src/apis/books/books.controller.ts
  frontend/apis/bookApi.ts
  frontend/components/common/Book/index.tsx
  frontend/components/home/Slider/index.tsx
  frontend/components/home/Slider/tempBookData.ts
  frontend/components/viewer/TOC/index.tsx
  frontend/interfaces/bookmark.interface.ts
  frontend/interfaces/index.ts
  frontend/interfaces/scrap.interface.ts
  frontend/interfaces/user.interface.ts
  frontend/pages/index.tsx
Labels: FEAT, BE, FE

#100 뷰어페이지 글 삭제 후 기능
  backend/src/apis/books/books.service.ts
  frontend/components/viewer/ArticleContent/index.tsx
  frontend/components/viewer/TOC/index.tsx
  frontend/components/viewer/TOC/styled.ts
  frontend/pages/viewer/[...data].tsx
Labels: FEAT, FE

#102 Content 컴포넌트 추가
  frontend/components/common/Content/index.tsx
  frontend/components/common/Content/styled.ts
  frontend/components/edit/Editor/index.tsx
  frontend/components/edit/Editor/styled.ts
  frontend/components/edit/Preview/index.tsx
  frontend/components/edit/Preview/styled.ts
Labels: FEAT, FE

#103 뷰어페이지 글 컴포넌트 교체
  frontend/components/viewer/ArticleContent/index.tsx
  frontend/components/viewer/TOC/index.tsx
  frontend/components/viewer/TOC/styled.ts
Labels: FEAT, FE

#104 에디터 페이지 책 데이터 패칭
  backend/src/apis/books/books.controller.ts
  frontend/apis/bookApi.ts
  frontend/components/edit/PublishModal/index.tsx
  frontend/interfaces/scrap.interface.ts
  frontend/pages/editor.tsx
Labels: FE, IMPROVE

#105 3주차 데모용 메인 수정
  frontend/components/common/Book/index.tsx
  frontend/components/common/Book/styled.ts
  frontend/components/common/GNB/index.tsx
  frontend/components/common/GNB/styled.ts
  frontend/components/study/BookListTab.tsx/index.tsx
  frontend/components/study/BookListTab/index.tsx
  frontend/components/study/BookListTab/styled.ts
  frontend/pages/study/[...data].tsx
  frontend/tsconfig.json
Labels: FEAT, FE

#107 CI/CD 작업
  .github/workflows/deploy-backend.yml
  .github/workflows/deploy-frontend.yml
  backend/package.json
  backend/pm2.json
  backend/tsconfig-paths.js
  backend/tsconfig.json
  frontend/.gitignore
  frontend/pm2.json
Labels: FEAT, BE, FE

#109 Lighthouse CI 작업
  .github/workflows/deploy-development-backend.yml
  .github/workflows/deploy-development-frontend.yml
  .github/workflows/pull-reqeust-frontend.yml
  frontend/.lighthouserc.js
Labels: FEAT, BE, FE

#108 뷰어페이지 사이드바 북마크 버그 수정
  frontend/apis/articleApi.ts
  frontend/apis/bookApi.ts
  frontend/pages/viewer/[...data].tsx
Labels: BUG, FE

#110 메인페이지 슬라이더 구현
  frontend/assets/ico_arrow_left.svg
  frontend/components/common/Book/index.tsx
  frontend/components/common/Book/styled.ts
  frontend/components/common/Modal/styled.ts
  frontend/components/home/Slider/index.tsx
  frontend/components/home/Slider/styled.ts
  frontend/components/study/BookListTab/index.tsx
  frontend/components/viewer/TOC/index.tsx
  frontend/interfaces/book.interface.ts
  frontend/interfaces/index.ts
  frontend/interfaces/user.interface.ts
  frontend/pages/index.tsx
Labels: FEAT, FE

#112 Editor 컴포넌트 이미지 붙여넣기 작업
  frontend/apis/imageApi.ts
  frontend/components/common/Content/styled.ts
  frontend/components/edit/Editor/core/theme.ts
  frontend/components/edit/Editor/core/useCodeMirror.ts
  frontend/components/edit/Editor/index.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/tsconfig.json
  frontend/utils/api.ts
Labels: FEAT, FE

#129 GitHub Action 워크 플로우 수정 작업
  .github/workflows/backend-cd.yml
  .github/workflows/frontend-cd.yml
  .github/workflows/frontend-ci.yml
Labels: IMPROVE, BUILD

#128 프론트엔드 인터페이스 정리 작업
  frontend/components/common/Book/index.tsx
  frontend/components/edit/PublishModal/index.tsx
  frontend/components/home/Slider/index.tsx
  frontend/components/study/BookListTab/index.tsx
  frontend/components/viewer/ArticleContent/index.tsx
  frontend/components/viewer/ScrapModal/index.tsx
  frontend/components/viewer/TOC/index.tsx
  frontend/interfaces/article.interface.ts
  frontend/interfaces/book.interface.ts
  frontend/interfaces/bookmark.interface.ts
  frontend/interfaces/combined.interface.ts
  frontend/interfaces/index.ts
  frontend/interfaces/scrap.interface.ts
  frontend/interfaces/user.interface.ts
Labels: FEAT, IMPROVE

#142 프론트엔드 이미지 파일 위치 수정 작업
  frontend/public/assets/ico_add.svg
  frontend/public/assets/ico_arrow_left.svg
  frontend/public/assets/ico_arrow_right.svg
  frontend/public/assets/ico_article.svg
  frontend/public/assets/ico_backward.svg
  frontend/public/assets/ico_bookmark.svg
  frontend/public/assets/ico_bookmark_black.svg
  frontend/public/assets/ico_bookmark_grey_filled.svg
  frontend/public/assets/ico_bookmark_red.svg
  frontend/public/assets/ico_bookmark_white_filled.svg
  frontend/public/assets/ico_cancel.svg
  frontend/public/assets/ico_caret_down.svg
  frontend/public/assets/ico_edit.svg
  frontend/public/assets/ico_edit_white.svg
  frontend/public/assets/ico_flower.svg
  frontend/public/assets/ico_github.svg
  frontend/public/assets/ico_hide.svg
  frontend/public/assets/ico_leftBtn.svg
  frontend/public/assets/ico_more_contents.svg
  frontend/public/assets/ico_open.svg
  frontend/public/assets/ico_original.svg
  frontend/public/assets/ico_person.svg
  frontend/public/assets/ico_rightBtn.svg
  frontend/public/assets/ico_sampleProfile.svg
  frontend/public/assets/ico_scrap.svg
  frontend/public/assets/ico_search.svg
  frontend/public/assets/ico_user1.svg
  frontend/public/assets/img_profile.png
  frontend/public/assets/img_sample_thumbnail.jpg
  frontend/tsconfig.json
Labels: FE, IMPROVE

#130 toast 메세지 추가, 로그인,회원가입 모달 수정
  frontend/apis/authApi.ts
  frontend/components/SignInModal/index.tsx
  frontend/components/SignUpModal/index.tsx
  frontend/components/common/GNB/index.tsx
  frontend/hooks/useFetch.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/utils/toast.ts
Labels: FEAT, FE, IMPROVE

#143 로그인 상태 유지, 로그아웃 구현
  backend/src/apis/auth/auth.controller.ts
  backend/src/apis/index.ts
  backend/src/utils/token.ts
  frontend/apis/authApi.ts
  frontend/atoms/signInStatus.ts
  frontend/components/CheckSignInByToken/index.tsx
  frontend/components/SignInModal/index.tsx
  frontend/components/common/GNB/index.tsx
  frontend/components/common/GNB/styled.ts
  frontend/components/home/Slider/index.tsx
  frontend/components/home/Slider/styled.ts
  frontend/components/study/UserProfile/index.tsx
  frontend/components/study/UserProfile/styled.ts
  frontend/pages/_app.tsx
  frontend/pages/github.tsx
Labels: FEAT, BE, FE

#144 글 검색 API 작업
  backend/src/apis/articles/articles.controller.ts
  backend/src/apis/articles/articles.interface.ts
  backend/src/apis/articles/articles.service.ts
  backend/src/apis/index.ts
Labels: FEAT, BE

#145 서버 책 검색 결과 반환 기능 구현
  backend/src/apis/books/books.controller.ts
  backend/src/apis/books/books.interface.ts
  backend/src/apis/books/books.service.ts
  backend/src/apis/index.ts
Labels: FEAT, BE

#146 검색 페이지 글 검색 요청 작업
  frontend/apis/articleApi.ts
  frontend/pages/search.tsx
Labels: FEAT, FE

#147 useDebounce 훅 추가 및 검색바에 훅 적용
  backend/src/apis/books/books.service.ts
  frontend/components/search/SearchBar/index.tsx
  frontend/hooks/useDebounce.ts
  frontend/pages/search.tsx
Labels: FEAT, FE

#148 책 검색 요청 작업
  frontend/apis/bookApi.ts
  frontend/pages/search.tsx
Labels: FEAT, FE

#152 검색 필터링 시 컴포넌트 전환 작업
  frontend/components/search/ArticleList/index.tsx
  frontend/components/search/BookList/index.tsx
  frontend/components/search/SearchFilter/index.tsx
  frontend/pages/search.tsx
Labels: FEAT, FE

#150 책 수정, 추가 모달 UI 작업
  frontend/components/common/Book/index.tsx
  frontend/components/common/Modal/styled.ts
  frontend/components/study/AddBook/index.tsx
  frontend/components/study/AddBook/styled.ts
  frontend/components/study/BookListTab/index.tsx
  frontend/components/study/EditBook/index.tsx
  frontend/components/study/EditBook/styled.ts
  frontend/components/study/FAB/index.tsx
  frontend/components/study/FAB/styled.ts
Labels: FEAT, FE

#151 책 생성 Api
  backend/src/apis/books/books.controller.ts
  backend/src/apis/books/books.interface.ts
  backend/src/apis/books/books.service.ts
  backend/src/apis/index.ts
Labels: FEAT, BE

#155 GitHub Code Owners 추가
  .github/codeowners
Labels: IMPROVE, BUILD

#149 검색 바 관련 작업
  backend/prisma/schema.prisma
  backend/src/apis/articles/articles.controller.ts
  backend/src/apis/articles/articles.interface.ts
  backend/src/apis/articles/articles.service.ts
  backend/src/apis/books/books.controller.ts
  backend/src/apis/books/books.interface.ts
  backend/src/apis/books/books.service.ts
  backend/src/apis/index.ts
  frontend/apis/articleApi.ts
  frontend/apis/bookApi.ts
  frontend/components/search/ArticleList/index.tsx
  frontend/components/search/BookList/index.tsx
  frontend/components/search/SearchBar/index.tsx
  frontend/components/search/SearchFilter/index.tsx
  frontend/hooks/useDebounce.ts
  frontend/pages/search.tsx
Labels: FEAT, BE, FE

#156 책 생성 기능 & 피드백 반영
  backend/src/apis/books/books.controller.ts
  frontend/apis/bookApi.ts
  frontend/components/common/Book/index.tsx
  frontend/components/study/AddBook/index.tsx
  frontend/components/study/BookListTab/index.tsx
  frontend/components/study/FAB/index.tsx
Labels: FEAT, FE, IMPROVE

#158 [BUG] 함수 메서드 이름 수정
  backend/package-lock.json
  backend/package.json
  backend/src/apis/index.ts
Labels: BUG, RELEASE

#159 [BUG] 함수 메서드 이름 수정
  .github/ISSUE_TEMPLATE/pull_request_template.md
  backend/package-lock.json
  backend/package.json
  backend/src/apis/index.ts
Labels: BUG, RELEASE

#154 useIntersectionObserver 훅 추가
  frontend/components/search/ArticleItem/index.tsx
  frontend/components/search/ArticleItem/styled.ts
  frontend/components/search/ArticleList/index.tsx
  frontend/components/search/SearchListItem/index.tsx
  frontend/hooks/useIntersectionObserver.ts
  frontend/interfaces/article.interface.ts
  frontend/pages/search.tsx
Labels: FEAT, FE

#174 서재 북 리스트 탭 작업
  backend/src/apis/books/books.controller.ts
  backend/src/apis/books/books.interface.ts
  backend/src/apis/books/books.service.ts
  frontend/apis/bookApi.ts
  frontend/components/study/BookListTab/index.tsx
  frontend/components/study/BookListTab/styled.ts
  frontend/components/study/EditUserProfile/index.tsx
  frontend/components/study/FAB/styled.ts
  frontend/pages/study/[...data].tsx
Labels: FEAT, BE, FE

#176 검색페이지 글, 책 무한스크롤 작업
  backend/src/apis/articles/articles.controller.ts
  backend/src/apis/articles/articles.service.ts
  backend/src/apis/books/books.controller.ts
  backend/src/apis/books/books.service.ts
  frontend/components/search/BookList/index.tsx
  frontend/components/search/BookList/styled.ts
  frontend/components/search/SearchFilter/index.tsx
  frontend/pages/search.tsx
Labels: FEAT, BE, FE

#171 Backend CI 작업
  .github/ISSUE_TEMPLATE/pull_request_template.md
  .github/workflows/backend-ci.yml
  backend/.eslintrc.js
  backend/package.json
  backend/src/loaders/express.loader.ts
Labels: FEAT, BUILD
