Repository boostcampwm-2022/web01-knoticle, pull requests merged in 2022-12, with the labels that each got.

#177 서재페이지 책 생성 및 삭제 구현
  backend/src/apis/books/books.controller.ts
  backend/src/apis/books/books.service.ts
  backend/src/apis/index.ts
  frontend/apis/bookApi.ts
  frontend/atoms/curKnottedBookList.ts
  frontend/atoms/editInfo.ts
  frontend/components/common/Book/index.tsx
  frontend/components/study/AddBook/index.tsx
  frontend/components/study/BookListTab/index.tsx
  frontend/components/study/BookListTab/styled.ts
  frontend/components/study/FAB/index.tsx
  frontend/components/study/FAB/styled.ts
  frontend/pages/study/[...data].tsx
  frontend/public/assets/ico_check_white.svg
  frontend/public/assets/ico_minus_white.svg
Labels: FEAT, BE, FE

#178 드래그앤드롭, 스크랩 api
  backend/src/apis/books/books.controller.ts
  backend/src/apis/books/books.service.ts
  backend/src/apis/scraps/scraps.interface.ts
  backend/src/apis/scraps/scraps.service.ts
  frontend/.eslintrc.json
  frontend/atoms/scrap.ts
  frontend/components/common/Book/index.tsx
  frontend/components/common/DragDrop/Container/index.tsx
  frontend/components/common/DragDrop/Container/styled.ts
  frontend/components/common/DragDrop/ListItem/index.tsx
  frontend/components/common/DragDrop/ListItem/styled.ts
  frontend/components/common/DragDrop/dndInterface.ts
  frontend/components/common/DragDrop/index.tsx
  frontend/components/study/EditBook/index.tsx
  frontend/interfaces/scrap.interface.ts
  frontend/package-lock.json
  frontend/package.json
Labels: FEAT, BE, FE

#181 서재 책 수정 API 요청 로직 수정
  backend/src/apis/books/books.controller.ts
  backend/src/apis/books/books.service.ts
  backend/src/apis/index.ts
  frontend/atoms/editInfo.ts
  frontend/components/study/AddBook/index.tsx
  frontend/components/study/BookListTab/index.tsx
  frontend/components/study/BookListTab/styled.ts
  frontend/components/study/EditBook/index.tsx
  frontend/components/study/EditUserProfile/styled.ts
  frontend/components/study/FAB/index.tsx
  frontend/components/study/UserProfile/styled.ts
Labels: BE, FE, IMPROVE

#180 검색어 강조 기능 작업
  backend/prisma/schema.prisma
  backend/src/apis/articles/articles.controller.ts
  backend/src/apis/books/books.controller.ts
  frontend/apis/articleApi.ts
  frontend/apis/bookApi.ts
  frontend/components/common/Book/styled.ts
  frontend/components/search/ArticleItem/styled.ts
  frontend/pages/search.tsx
Labels: FEAT, BE, FE

#183 에디터 발행 모달 드래그앤드롭 적용
  backend/src/apis/articles/articles.controller.ts
  backend/src/apis/articles/articles.service.ts
  backend/src/apis/books/books.controller.ts
  backend/src/apis/scraps/scraps.service.ts
  frontend/atoms/article.ts
  frontend/components/common/Book/index.tsx
  frontend/components/edit/PublishModal/index.tsx
Labels: FEAT, BE, FE

#182 UI 수정 작업
  frontend/components/common/Book/index.tsx
  frontend/components/common/Book/styled.ts
  frontend/components/common/Content/styled.ts
  frontend/components/common/GNB/styled.ts
  frontend/components/common/Modal/styled.ts
  frontend/components/home/Slider/styled.ts
  frontend/components/search/SearchBar/index.tsx
  frontend/components/search/SearchBar/styled.ts
  frontend/components/search/SearchNoResult/index.tsx
  frontend/components/search/SearchNoResult/styled.ts
  frontend/components/viewer/ArticleContent/styled.ts
  frontend/components/viewer/TOC/styled.ts
  frontend/pages/search.tsx
  frontend/styles/layout.ts
Labels: FE, IMPROVE

#184 에디터 바 위치 수정 작업
  frontend/components/edit/EditBar/styled.ts
  frontend/components/edit/Editor/index.tsx
  frontend/components/edit/Editor/styled.ts
  frontend/pages/editor.tsx
Labels: FE, IMPROVE

#185 검색 결과 클릭 시 특정 페이지로 이동하는 작업
  backend/src/apis/articles/articles.service.ts
  frontend/components/search/ArticleItem/index.tsx
  frontend/components/search/ArticleList/index.tsx
  frontend/styles/GlobalStyle.ts
Labels: FEAT, FE

#188 스크랩 모달 순서 선택 기능 추가
  backend/src/apis/scraps/scraps.controller.ts
  frontend/components/common/Book/styled.ts
  frontend/components/study/FAB/index.tsx
  frontend/components/viewer/ScrapModal/index.tsx
  frontend/components/viewer/ScrapModal/styled.ts
  frontend/pages/editor.tsx
  frontend/pages/viewer/[...data].tsx
Labels: FEAT, BE, FE

#189 release-1201 반영
  backend/src/apis/articles/articles.controller.ts
  backend/src/apis/articles/articles.service.ts
  backend/src/apis/books/books.controller.ts
  backend/src/apis/books/books.interface.ts
  backend/src/apis/books/books.service.ts
  backend/src/apis/index.ts
  backend/src/apis/scraps/scraps.controller.ts
  backend/src/apis/scraps/scraps.interface.ts
  backend/src/apis/scraps/scraps.service.ts
  frontend/apis/bookApi.ts
  frontend/atoms/article.ts
  frontend/atoms/curKnottedBookList.ts
  frontend/atoms/editInfo.ts
  frontend/atoms/scrap.ts
  frontend/components/common/Book/index.tsx
  frontend/components/common/Book/styled.ts
  frontend/components/common/DragDrop/Container/index.tsx
  frontend/components/common/DragDrop/Container/styled.ts
  frontend/components/common/DragDrop/ListItem/index.tsx
  frontend/components/common/DragDrop/ListItem/styled.ts
  frontend/components/common/DragDrop/dndInterface.ts
  frontend/components/common/DragDrop/index.tsx
  frontend/components/common/Dropdown/index.tsx
  frontend/components/edit/PublishModal/index.tsx
  frontend/components/edit/PublishModal/styled.ts
  frontend/components/study/AddBook/index.tsx
  frontend/components/study/BookListTab/index.tsx
  frontend/components/study/BookListTab/styled.ts
  frontend/components/study/EditBook/index.tsx
  frontend/components/study/EditBook/styled.ts
  frontend/components/study/EditUserProfile/index.tsx
  frontend/components/study/EditUserProfile/styled.ts
  frontend/components/study/FAB/index.tsx
  frontend/components/study/FAB/styled.ts
  frontend/components/study/UserProfile/styled.ts
  frontend/components/viewer/ScrapModal/index.tsx
  frontend/components/viewer/ScrapModal/styled.ts
  frontend/interfaces/book.interface.ts
  frontend/interfaces/scrap.interface.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/editor.tsx
  frontend/pages/study/[...data].tsx
  frontend/pages/viewer/[...data].tsx
  frontend/public/assets/ico_check_white.svg
  frontend/public/assets/ico_minus_white.svg
Labels: RELEASE

#192 README 추가
  README.md
Labels: DOCS

#202 페이지 타이틀, 메타 태그 추가 작업
  frontend/components/edit/EditHead/index.tsx
  frontend/components/home/HomeHead/index.tsx
  frontend/components/search/SearchHead/index.tsx
  frontend/components/study/StudyHead/index.tsx
  frontend/components/viewer/ViewerHead/index.tsx
  frontend/pages/editor.tsx
  frontend/pages/index.tsx
  frontend/pages/search.tsx
  frontend/pages/study/[...data].tsx
Labels: FEAT, FE

#204 사이트맵 및 robots.txt 추가 작업
  backend/src/apis/index.ts
  backend/src/apis/scraps/scraps.controller.ts
  backend/src/apis/scraps/scraps.service.ts
  frontend/apis/scrapApi.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/sitemap.xml.tsx
  frontend/public/robots.txt
Labels: FEAT, FE

#205 뷰어 페이지 SSR 적용 및 폰트 로딩 수정
  frontend/pages/_app.tsx
  frontend/pages/_document.tsx
  frontend/pages/viewer/[...data].tsx
  frontend/styles/font.css
  frontend/styles/sofia.woff2
Labels: FE, IMPROVE

#211 에디터 페이지 나가기 버튼 작업
  frontend/components/edit/EditBar/index.tsx
Labels: FEAT, FE

#210 뷰어페이지 프로필 Link
  frontend/components/viewer/TOC/index.tsx
  frontend/components/viewer/TOC/styled.ts
Labels: FEAT, FE

#217 메인페이지 Skeleton UI 적용
  frontend/components/SkeletonBook/index.tsx
  frontend/components/SkeletonBook/styled.ts
  frontend/components/home/Slider/index.tsx
  frontend/hooks/useFetch.ts
  frontend/pages/index.tsx
Labels: FE, IMPROVE

#213 4주차 데모 배포 버그 수정 사항 - auth 로직, 서재 수정모드
  backend/src/apis/auth/auth.service.ts
  frontend/atoms/scrap.ts
  frontend/components/common/DragDrop/Container/index.tsx
  frontend/components/edit/PublishModal/index.tsx
  frontend/components/study/AddBook/index.tsx
  frontend/components/study/BookListTab/index.tsx
  frontend/components/study/EditBook/index.tsx
  frontend/components/study/EditUserProfile/index.tsx
  frontend/components/study/EditUserProfile/styled.ts
  frontend/components/study/FAB/index.tsx
  frontend/components/viewer/ScrapModal/index.tsx
  frontend/interfaces/scrap.interface.ts
  frontend/pages/github.tsx
Labels: BE, FE, IMPROVE

#214 에디터 페이지 글 저장 및 불러오기 작업
  backend/src/apis/articles/articles.controller.ts
  backend/src/apis/index.ts
  frontend/apis/articleApi.ts
  frontend/atoms/articleBuffer.ts
  frontend/components/edit/EditBar/index.tsx
  frontend/components/edit/Editor/core/useCodeMirror.ts
  frontend/components/edit/Editor/index.tsx
  frontend/hooks/useInput.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/utils/parser.ts
Labels: FEAT, BE, FE, IMPROVE

#215 책, 글 삭제 기능
  backend/src/apis/articles/articles.controller.ts
  backend/src/apis/books/books.controller.ts
  backend/src/apis/books/books.service.ts
  backend/src/apis/index.ts
  backend/src/apis/scraps/scraps.controller.ts
  backend/src/apis/scraps/scraps.service.ts
  frontend/apis/articleApi.ts
  frontend/apis/scrapApi.ts
  frontend/atoms/article.ts
  frontend/atoms/curKnottedBookList.ts
  frontend/atoms/editInfo.ts
  frontend/atoms/scrap.ts
  frontend/components/common/Book/index.tsx
  frontend/components/common/DragDrop/Container/index.tsx
  frontend/components/common/DragDrop/Container/styled.ts
  frontend/components/common/DragDrop/ListItem/index.tsx
  frontend/components/common/DragDrop/ListItem/styled.ts
  frontend/components/common/DragDrop/dndInterface.ts
  frontend/components/common/DragDrop/index.tsx
  frontend/components/edit/PublishModal/index.tsx
  frontend/components/study/AddBook/index.tsx
  frontend/components/study/BookListTab/index.tsx
  frontend/components/study/EditBook/index.tsx
  frontend/components/study/EditBook/styled.ts
  frontend/components/study/FAB/index.tsx
  frontend/components/viewer/ScrapModal/index.tsx
  frontend/interfaces/combined.interface.ts
  frontend/interfaces/index.ts
  frontend/interfaces/scrap.interface.ts
Labels: FEAT, BE, FE

#220 검색 기능 개선 작업
  backend/prisma/schema.prisma
  backend/src/apis/articles/articles.service.ts
  backend/src/apis/books/books.service.ts
Labels: BE, IMPROVE

#227 공통 반응형 스타일 작업
  frontend/pages/_app.tsx
  frontend/styles/responsive.ts
Labels: FEAT, FE

#230 책 컴포넌트 반응형 작업
  frontend/components/common/Book/index.tsx
  frontend/components/common/Book/styled.ts
  frontend/components/study/BookListTab/styled.ts
  frontend/pages/booktest.tsx
  frontend/styles/layout.ts
Labels: FEAT, FE

#228 스크랩 관련 버그 수정 및 PR 리뷰 사항 반영
  backend/src/apis/articles/articles.controller.ts
  backend/src/apis/index.ts
  frontend/components/edit/ModifyModal/index.tsx
  frontend/components/edit/ModifyModal/styled.ts
  frontend/components/viewer/ScrapModal/index.tsx
  frontend/components/viewer/ScrapModal/styled.ts
  frontend/pages/editor.tsx
  frontend/pages/viewer/[...data].tsx
Labels: BUG, IMPROVE

#238 GitHub 로그인 대기 페이지 UI/UX 개선 작업
  frontend/components/SignInModal/styled.ts
  frontend/components/common/Spinner/index.tsx
  frontend/components/common/Spinner/styled.ts
  frontend/components/study/EditBook/styled.ts
  frontend/pages/github.tsx
  frontend/styles/layout.ts
  frontend/tsconfig.json
Labels: FEAT, FE, IMPROVE

#234 서재페이지, 드래그앤드롭 반응형 작업
  frontend/components/common/DragDrop/index.tsx
  frontend/components/study/UserProfile/styled.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/styles/GlobalStyle.ts
Labels: FEAT, FE

#235 메인페이지 반응형 적용
  frontend/components/common/SkeletonBook/index.tsx
  frontend/components/common/SkeletonBook/styled.ts
  frontend/components/home/Slider/index.tsx
  frontend/components/home/Slider/styled.ts
  frontend/components/home/Slider/tempBookData.ts
  frontend/pages/index.tsx
Labels: FEAT, FE, IMPROVE

#239 개선 사항 작업
  backend/src/errors/message.ts
  frontend/components/common/Book/index.tsx
  frontend/components/common/Book/styled.ts
  frontend/components/viewer/ArticleContent/index.tsx
  frontend/public/assets/ico_bookmark_black.svg
  frontend/public/assets/ico_bookmark_grey_filled.svg
Labels: FE, IMPROVE

#240 Auth 관련 컴포넌트 위치 변경 작업
  frontend/components/auth/CheckSignInStatus/index.tsx
  frontend/components/auth/SignInModal/index.tsx
  frontend/components/auth/SignInModal/styled.ts
  frontend/components/auth/SignUpModal/index.tsx
  frontend/components/auth/SignUpModal/styled.ts
  frontend/components/common/GNB/index.tsx
  frontend/pages/_app.tsx
Labels: FE, IMPROVE

#241 백엔드 Eslint 룰 추가 및 코드 정리 작업
  backend/.eslintrc.js
  backend/src/apis/articles/articles.controller.ts
  backend/src/apis/articles/articles.service.ts
  backend/src/apis/auth/auth.controller.ts
  backend/src/apis/auth/auth.service.ts
  backend/src/apis/bookmarks/bookmarks.controller.ts
  backend/src/apis/bookmarks/bookmarks.service.ts
  backend/src/apis/books/books.controller.ts
  backend/src/apis/books/books.service.ts
  backend/src/apis/images/images.controller.ts
  backend/src/apis/index.ts
  backend/src/apis/scraps/scraps.controller.ts
  backend/src/apis/scraps/scraps.service.ts
  backend/src/apis/users/users.controller.ts
  backend/src/apis/users/users.service.ts
  backend/src/loaders/express.loader.ts
  backend/src/middlewares/tokenValidator.ts
  backend/src/utils/token.ts
Labels: BE, IMPROVE

#251 뷰어페이지 반응형 작업
  frontend/components/viewer/ArticleContent/Button/styled.ts
  frontend/components/viewer/ArticleContent/index.tsx
  frontend/components/viewer/ArticleContent/styled.ts
  frontend/components/viewer/ClosedSideBar/styled.ts
  frontend/components/viewer/TOC/styled.ts
  frontend/pages/viewer/[...data].tsx
Labels: FEAT, FE

#249 에디터 페이지 반응형 작업
  frontend/components/edit/Editor/styled.ts
Labels: FEAT, FE

#252 에디터 스타일 개선 작업
  frontend/components/edit/Editor/core/theme.ts
  frontend/components/edit/Editor/core/useCodeMirror.ts
  frontend/package-lock.json
  frontend/package.json
Labels: FEAT, FE

#255 서재 페이지 프로필 & FE 간단한 수정
  frontend/components/study/BookListTab/index.tsx
  frontend/components/study/EditUserProfile/styled.ts
  frontend/components/study/UserProfile/styled.ts
  frontend/components/viewer/ArticleContent/index.tsx
  frontend/pages/viewer/[...data].tsx
Labels: FE, IMPROVE

#259 Content 컴포넌트 스타일 작업
  frontend/components/common/Content/styled.ts
  frontend/components/edit/Editor/core/theme.ts
  frontend/pages/sitemap.xml.tsx
Labels: FEAT, FE

#260 0.3.1 배포
  frontend/components/common/Content/styled.ts
  frontend/components/edit/Editor/core/theme.ts
  frontend/pages/sitemap.xml.tsx
Labels: RELEASE

#273 글 검색 결과에 HTML 태그가 들어있는 오류 수정 작업
  frontend/pages/search.tsx
Labels: BUG, IMPROVE

#263 Syntax Highlighting 작업
  frontend/components/common/Content/index.tsx
  frontend/components/common/Content/styled.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/utils/parser.ts
Labels: FEAT, BUG, FE, IMPROVE

#262 뷰어페이지 스크랩 삭제 기능
  backend/src/apis/books/books.service.ts
  backend/src/apis/index.ts
  backend/src/apis/scraps/scraps.controller.ts
  frontend/apis/scrapApi.ts
  frontend/components/common/Book/index.tsx
  frontend/components/study/BookListTab/index.tsx
  frontend/components/viewer/ArticleContent/index.tsx
  frontend/pages/booktest.tsx
  frontend/pages/viewer/[...data].tsx
Labels: FEAT, FE

#270 메인페이지 UI 및 모바일 대응 수정
  frontend/components/common/GNB/index.tsx
  frontend/components/common/GNB/styled.ts
  frontend/components/home/Slider/styled.ts
  frontend/pages/index.tsx
Labels: FE, IMPROVE

#276 에디터 리스트 태그 줄바꿈 오류 수정 작업
  frontend/components/common/Content/styled.ts
Labels: BUG, IMPROVE

#275 검색 결과 책 표시 오류 및 뷰어페이지 이중스크롤 버그 해결
  frontend/components/common/Book/index.tsx
  frontend/components/common/Book/styled.ts
  frontend/components/edit/Editor/styled.ts
  frontend/components/viewer/ArticleContent/styled.ts
  frontend/components/viewer/ClosedSideBar/styled.ts
  frontend/components/viewer/TOC/styled.ts
  frontend/pages/editor.tsx
  frontend/pages/search.tsx
  frontend/pages/viewer/[...data].tsx
  frontend/styles/layout.ts
Labels: BUG, IMPROVE

#272 뷰어페이지 스크랩 버그 수정
  backend/src/apis/scraps/scraps.controller.ts
  frontend/components/viewer/ScrapModal/index.tsx
  frontend/pages/viewer/[...data].tsx
Labels: BUG, FE, IMPROVE

#278 책이나 글의 제목을 비워놓을 수 있는 오류 수정 작업
  backend/package-lock.json
  backend/package.json
  backend/prisma/schema.prisma
  backend/src/apis/articles/articles.controller.ts
  backend/src/apis/books/books.controller.ts
  backend/src/errors/message.ts
Labels: BUG, IMPROVE

#279 0.3.2 배포
  backend/package-lock.json
  backend/package.json
  backend/prisma/schema.prisma
  backend/src/apis/articles/articles.controller.ts
  backend/src/apis/books/books.controller.ts
  backend/src/apis/books/books.service.ts
  backend/src/apis/index.ts
  backend/src/apis/scraps/scraps.controller.ts
  backend/src/errors/message.ts
  frontend/apis/scrapApi.ts
  frontend/components/common/Book/index.tsx
  frontend/components/common/Book/styled.ts
  frontend/components/common/Content/index.tsx
  frontend/components/common/Content/styled.ts
  frontend/components/common/GNB/index.tsx
  frontend/components/common/GNB/styled.ts
  frontend/components/edit/Editor/styled.ts
  frontend/components/home/Slider/styled.ts
  frontend/components/study/BookListTab/index.tsx
  frontend/components/viewer/ArticleContent/index.tsx
  frontend/components/viewer/ArticleContent/styled.ts
  frontend/components/viewer/ClosedSideBar/styled.ts
  frontend/components/viewer/ScrapModal/index.tsx
  frontend/components/viewer/TOC/styled.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/booktest.tsx
  frontend/pages/editor.tsx
  frontend/pages/index.tsx
  frontend/pages/search.tsx
  frontend/pages/viewer/[...data].tsx
  frontend/styles/layout.ts
  frontend/utils/parser.ts
Labels: RELEASE

#280 콘텐츠 관련 스타일 수정 작업
  frontend/components/common/Content/styled.ts
  frontend/components/search/ArticleItem/styled.ts
  frontend/components/viewer/ArticleContent/index.tsx
  frontend/components/viewer/ArticleContent/styled.ts
Labels: FE, IMPROVE

#281 글 검색 시 글 내용에 검색어가 나타나도록 문자열 파싱 작업
  frontend/pages/search.tsx
Labels: FEAT, BUG, FE, IMPROVE

#283 0.3.3 배포
  .github/workflows/sitemap-ping.yml
  frontend/components/common/Content/styled.ts
  frontend/components/search/ArticleItem/styled.ts
  frontend/components/viewer/ArticleContent/index.tsx
  frontend/components/viewer/ArticleContent/styled.ts
  frontend/pages/search.tsx
Labels: RELEASE

#284 docs: README.md 수정
  README.md
Labels: DOCS, IMPROVE

#285 docs: README.md 수정
  README.md
Labels: DOCS, IMPROVE

#288 수정모달 개선 작업
  frontend/components/common/DragDrop/ListItem/index.tsx
  frontend/components/common/DragDrop/ListItem/styled.ts
  frontend/components/study/EditBook/index.tsx
  frontend/components/study/EditBook/styled.ts
  frontend/styles/GlobalStyle.ts
Labels: FE, IMPROVE

#289 사이드 바 UI/UX 개선 작업
  frontend/components/viewer/ClosedSideBar/index.tsx
  frontend/components/viewer/ClosedSideBar/styled.ts
  frontend/components/viewer/TOC/index.tsx
  frontend/components/viewer/TOC/styled.ts
  frontend/pages/viewer/[...data].tsx
  frontend/public/assets/ico_open.svg
  frontend/styles/layout.ts
Labels: FEAT, FE, IMPROVE

#290 글 검색 결과에 프로필 사진이 반영되지 않는 오류 수정 작업
  frontend/components/search/ArticleItem/index.tsx
  frontend/components/search/ArticleList/index.tsx
  frontend/public/assets/img_profile.png
Labels: FE, IMPROVE

#291 Lighthouse CI 개선 및 Lighthouse 피드백 반영
  .github/workflows/frontend-ci.yml
  frontend/.lighthouserc.js
  frontend/components/common/GNB/index.tsx
  frontend/components/study/BookListTab/index.tsx
  frontend/components/study/EditBookModal/index.tsx
  frontend/components/study/EditBookModal/styled.ts
  frontend/pages/_document.tsx
  frontend/pages/editor.tsx
  frontend/pages/viewer/[...data].tsx
Labels: FE, IMPROVE, BUILD

#295 무중단 배포 작업
  backend/pm2.json
  backend/src/index.ts
  frontend/pm2.json
Labels: FEAT, BUILD

#293 글 목차 기능
  frontend/components/viewer/ArticleContent/index.tsx
  frontend/components/viewer/TOC/index.tsx
  frontend/components/viewer/TOC/styled.ts
  frontend/pages/viewer/[...data].tsx
  frontend/utils/articleConversion.ts
Labels: FEAT, FE

#297 클라이언트 책 생성, 수정 시 빈 제목 방지
  frontend/components/study/AddBook/index.tsx
  frontend/components/study/EditBookModal/index.tsx
Labels: FE, IMPROVE

#296 서재 페이지 북마크 클릭 미반영 및 무한클릭 방지
  backend/src/apis/bookmarks/bookmarks.controller.ts
  backend/src/apis/bookmarks/bookmarks.service.ts
  backend/src/errors/message.ts
  frontend/atoms/curBookmarkedBookList.ts
  frontend/components/common/Book/index.tsx
  frontend/components/study/FAB/index.tsx
  frontend/components/viewer/TOC/index.tsx
  frontend/hooks/useBookmark.ts
  frontend/pages/study/[...data].tsx
Labels: BE, FE, IMPROVE

#292 뷰어페이지 GNB 모바일 대응 및 푸터, 수정 모달 개선 작업
  frontend/components/common/Footer/index.tsx
  frontend/components/common/Footer/styled.ts
  frontend/components/edit/ModifyModal/index.tsx
  frontend/components/viewer/ArticleContent/index.tsx
  frontend/components/viewer/ArticleContent/styled.ts
  frontend/components/viewer/TOC/index.tsx
  frontend/components/viewer/TOC/styled.ts
  frontend/hooks/useScrollDetector.ts
  frontend/pages/viewer/[...data].tsx
  frontend/public/robots.txt
  frontend/styles/layout.ts
Labels: FE, IMPROVE

#301 검색페이지 검색 결과 및 스크롤 보존 작업
  frontend/components/search/ArticleItem/index.tsx
  frontend/components/search/ArticleList/index.tsx
  frontend/components/search/BookList/index.tsx
  frontend/components/search/SearchFilter/index.tsx
  frontend/hooks/useSessionStorage.ts
  frontend/pages/search.tsx
  frontend/styles/layout.ts
Labels: FE, IMPROVE

#300 에디터 고도화 작업
  frontend/.eslintrc.json
  frontend/components/common/Content/styled.ts
  frontend/components/edit/Editor/core/theme.ts
  frontend/components/edit/Editor/core/useCodeMirror.ts
  frontend/components/edit/Editor/index.tsx
  frontend/components/edit/Editor/styled.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/editor.tsx
  frontend/public/assets/ico_bold.svg
  frontend/public/assets/ico_code.svg
  frontend/public/assets/ico_h1.svg
  frontend/public/assets/ico_h2.svg
  frontend/public/assets/ico_h3.svg
  frontend/public/assets/ico_image.svg
  frontend/public/assets/ico_italic.svg
  frontend/public/assets/ico_link.svg
  frontend/public/assets/ico_quote.svg
  frontend/public/assets/ico_strikethrough.svg
  frontend/utils/parser.ts
Labels: FE, IMPROVE

#309 개선사항 작업 및 책 검색 결과 반영 안 되는 버그 수정
  backend/prisma/schema.prisma
  backend/src/apis/articles/articles.controller.ts
  backend/src/apis/articles/articles.interface.ts
  backend/src/apis/articles/articles.service.ts
  backend/src/apis/books/books.controller.ts
  backend/src/apis/books/books.interface.ts
  backend/src/apis/books/books.service.ts
  backend/src/apis/index.ts
  frontend/apis/articleApi.ts
  frontend/apis/bookApi.ts
  frontend/components/common/LabeledInput/styled.ts
  frontend/components/search/SearchFilter/index.tsx
  frontend/components/viewer/ArticleContent/index.tsx
  frontend/pages/search.tsx
  frontend/public/favicon.ico
Labels: BUG

#304 수정모달, 뷰어페이지 개선 작업, Toast 메세지 추가
  frontend/components/common/Book/styled.ts
  frontend/components/edit/ModifyModal/index.tsx
  frontend/components/edit/PublishModal/index.tsx
  frontend/components/study/EditBookModal/index.tsx
  frontend/components/study/UserProfile/styled.ts
  frontend/components/viewer/ScrapModal/index.tsx
  frontend/components/viewer/TOC/index.tsx
  frontend/components/viewer/TOC/styled.ts
  frontend/utils/toast.ts
Labels: FE, IMPROVE

#313 서재페이지 수정모달 스크랩 버그 수정
  frontend/components/common/DragDrop/Container/index.tsx
  frontend/components/common/DragDrop/ListItem/index.tsx
  frontend/components/common/DragDrop/index.tsx
  frontend/components/edit/ModifyModal/index.tsx
  frontend/components/edit/PublishModal/index.tsx
  frontend/components/study/BookListTab/index.tsx
  frontend/components/study/EditBookModal/index.tsx
  frontend/components/viewer/ScrapModal/index.tsx
Labels: BUG, FE

#310 에디터 페이지 UI/UX 개선 작업
  frontend/components/common/Content/styled.ts
  frontend/components/edit/EditBar/index.tsx
  frontend/components/edit/EditBar/styled.ts
  frontend/public/assets/ico_exit.svg
Labels: FE, IMPROVE

#311 뷰어 페이지 사이드 바 TOC 개선 및 버그 수정 작업
  frontend/components/viewer/TOC/styled.ts
  frontend/utils/articleConversion.ts
Labels: BUG, FE, IMPROVE

#314 수정 모드 토스트 메시지 및 스크랩 수정
  backend/src/apis/articles/articles.controller.ts
  backend/src/apis/articles/articles.service.ts
  backend/src/apis/scraps/scraps.controller.ts
  backend/src/apis/scraps/scraps.service.ts
  frontend/apis/articleApi.ts
  frontend/components/common/DragDrop/ListItem/styled.ts
  frontend/components/study/BookListTab/index.tsx
  frontend/components/study/FAB/index.tsx
  frontend/components/viewer/ArticleContent/index.tsx
Labels: FE, IMPROVE

#315 삭제된 글 접근 버그 수정
  frontend/pages/viewer/[...data].tsx
Labels: BUG, FE

#316 Markdown 및 Html 관련 에디터 플로우 변경 작업
  frontend/components/common/Content/index.tsx
  frontend/components/edit/Editor/index.tsx
  frontend/components/search/ArticleList/index.tsx
  frontend/components/viewer/TOC/index.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/viewer/[...data].tsx
  frontend/utils/parser.ts
  frontend/utils/toc.ts
Labels: FEAT, BUG, FE, IMPROVE

#317 0.5.0 배포
  backend/prisma/schema.prisma
  backend/src/apis/articles/articles.controller.ts
  backend/src/apis/articles/articles.interface.ts
  backend/src/apis/articles/articles.service.ts
  backend/src/apis/books/books.controller.ts
  backend/src/apis/books/books.interface.ts
  backend/src/apis/books/books.service.ts
  backend/src/apis/index.ts
  backend/src/apis/scraps/scraps.controller.ts
  backend/src/apis/scraps/scraps.service.ts
  backend/src/middlewares/tokenErrorHandler.ts
  frontend/apis/articleApi.ts
  frontend/apis/bookApi.ts
  frontend/components/common/Book/styled.ts
  frontend/components/common/Content/index.tsx
  frontend/components/common/Content/styled.ts
  frontend/components/common/DragDrop/Container/index.tsx
  frontend/components/common/DragDrop/ListItem/index.tsx
  frontend/components/common/DragDrop/ListItem/styled.ts
  frontend/components/common/DragDrop/index.tsx
  frontend/components/common/LabeledInput/styled.ts
  frontend/components/edit/EditBar/index.tsx
  frontend/components/edit/EditBar/styled.ts
  frontend/components/edit/Editor/index.tsx
  frontend/components/edit/ModifyModal/index.tsx
  frontend/components/edit/PublishModal/index.tsx
  frontend/components/home/Slider/index.tsx
  frontend/components/home/Slider/styled.ts
  frontend/components/search/ArticleList/index.tsx
  frontend/components/search/SearchFilter/index.tsx
  frontend/components/study/BookListTab/index.tsx
  frontend/components/study/EditBookModal/index.tsx
  frontend/components/study/FAB/index.tsx
  frontend/components/study/UserProfile/styled.ts
  frontend/components/viewer/ArticleContent/index.tsx
  frontend/components/viewer/ScrapModal/index.tsx
  frontend/components/viewer/TOC/index.tsx
  frontend/components/viewer/TOC/styled.ts
  frontend/hooks/useSessionStorage.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/search.tsx
  frontend/pages/viewer/[...data].tsx
  frontend/public/assets/ico_exit.svg
  frontend/public/favicon.ico
  frontend/utils/articleConversion.ts
  frontend/utils/parser.ts
  frontend/utils/toast.ts
  frontend/utils/toc.ts
Labels: RELEASE

#318 검색 키워드 강조 로직 개선 작업
  frontend/components/search/ArticleList/index.tsx
  frontend/components/search/BookList/index.tsx
  frontend/utils/highlight-keyword.tsx
Labels: FE, IMPROVE

#319 v0.5.0 개선사항 수정
  frontend/components/common/Content/styled.ts
  frontend/components/common/DragDrop/ListItem/index.tsx
  frontend/components/common/DragDrop/ListItem/styled.ts
  frontend/components/edit/ModifyModal/index.tsx
  frontend/components/edit/ModifyModal/styled.ts
  frontend/components/edit/PublishModal/index.tsx
  frontend/components/edit/PublishModal/styled.ts
  frontend/components/search/ArticleItem/index.tsx
  frontend/components/search/ArticleItem/styled.ts
  frontend/components/study/EditUserProfile/styled.ts
  frontend/components/study/UserProfile/styled.ts
  frontend/components/viewer/ArticleContent/Button/styled.ts
  frontend/components/viewer/ArticleContent/index.tsx
  frontend/components/viewer/ArticleContent/styled.ts
  frontend/components/viewer/ScrapModal/index.tsx
  frontend/components/viewer/ScrapModal/styled.ts
  frontend/components/viewer/TOC/index.tsx
  frontend/components/viewer/TOC/styled.ts
Labels: FE, IMPROVE

#320 0.5.1 배포
  frontend/components/common/Content/styled.ts
  frontend/components/common/DragDrop/ListItem/index.tsx
  frontend/components/common/DragDrop/ListItem/styled.ts
  frontend/components/edit/ModifyModal/index.tsx
  frontend/components/edit/ModifyModal/styled.ts
  frontend/components/edit/PublishModal/index.tsx
  frontend/components/edit/PublishModal/styled.ts
  frontend/components/search/ArticleItem/index.tsx
  frontend/components/search/ArticleItem/styled.ts
  frontend/components/search/ArticleList/index.tsx
  frontend/components/search/BookList/index.tsx
  frontend/components/study/EditUserProfile/styled.ts
  frontend/components/study/UserProfile/styled.ts
  frontend/components/viewer/ArticleContent/Button/styled.ts
  frontend/components/viewer/ArticleContent/index.tsx
  frontend/components/viewer/ArticleContent/styled.ts
  frontend/components/viewer/ScrapModal/index.tsx
  frontend/components/viewer/ScrapModal/styled.ts
  frontend/components/viewer/TOC/index.tsx
  frontend/components/viewer/TOC/styled.ts
  frontend/utils/highlight-keyword.tsx
Labels: RELEASE

#321 슬라이더 touch 사선 방향 방지
  frontend/components/home/Slider/index.tsx
Labels: FE, IMPROVE

#322 v0.5.1 피드백 반영 작업
  frontend/components/common/Content/styled.ts
  frontend/components/viewer/TOC/index.tsx
  frontend/components/viewer/TOC/styled.ts
  frontend/utils/articleConversion.ts
  frontend/utils/highlight-keyword.tsx
  frontend/utils/toc.ts
Labels: BUG, FE, IMPROVE

#323 0.5.2 배포
  frontend/components/common/Content/styled.ts
  frontend/components/home/Slider/index.tsx
  frontend/components/viewer/TOC/index.tsx
  frontend/components/viewer/TOC/styled.ts
  frontend/utils/articleConversion.ts
  frontend/utils/highlight-keyword.tsx
  frontend/utils/toc.ts
Labels: RELEASE
